// One-time catalogue import source. These records are migrated to Atlas on server
// startup. Contains ALL businesses from the frontend dummy data + original B2B businesses.

export const catalogBusinesses = [
  // === Original B2B Businesses from data.js ===
  { id: 'b1', name: 'UrbanNest Interiors', category: 'Interior Design', subCategory: 'Home Renovation', type: 'Service', city: 'Mumbai', state: 'Maharashtra', pincode: '400001', address: 'Fort, Mumbai', area: 'Fort', serviceAreas: ['Mumbai', 'Thane', 'Navi Mumbai'], budgetMin: 50000, budgetMax: 800000, rating: 4.8, responseTimeMins: 18, conversionRate: 34, revenue: 1250000, profileCompletion: 92, approved: true, kycStatus: 'verified', verifiedBadge: true, credits: 42, plan: 'Premium', usp: 'End-to-end interiors with transparent milestones.', workingHours: 'Mon-Sat, 10 AM - 7 PM', emergencyAvailable: true, socials: { facebook: 'connected', instagram: 'connected', whatsapp: 'connected' }, seo: { title: 'UrbanNest Interiors Mumbai', keywords: ['interior designer', '2BHK renovation', 'modular kitchen'] }, website: { slug: 'urbannest', customDomain: '', theme: 'clean', published: true }, services: ['Interior Design', 'Home Renovation', 'Modular Kitchen'], priceRange: '₹₹₹' },
  { id: 'b2', name: 'SwiftFix Plumbing', category: 'Home Services', subCategory: 'Plumbing', type: 'Service', city: 'Pune', state: 'Maharashtra', pincode: '411001', address: 'Koregaon Park, Pune', area: 'Koregaon Park', serviceAreas: ['Pune', 'PCMC'], budgetMin: 500, budgetMax: 25000, rating: 4.5, responseTimeMins: 9, conversionRate: 41, revenue: 420000, profileCompletion: 74, approved: false, kycStatus: 'pending', verifiedBadge: false, credits: 11, plan: 'Pro', usp: 'Emergency repairs with same-day visits.', workingHours: 'All days, 8 AM - 10 PM', emergencyAvailable: true, socials: { facebook: 'not_connected', instagram: 'connected', whatsapp: 'connected' }, seo: { title: 'Emergency Plumber Pune', keywords: ['plumber near me', 'leak repair'] }, website: { slug: 'swiftfix', customDomain: '', theme: 'bold', published: false }, services: ['Plumbing', 'AC Repair', 'Electrical'], priceRange: '₹' },
  { id: 'b3', name: 'PixelLaunch Marketing', category: 'Digital Marketing', subCategory: 'Performance Ads', type: 'Service', city: 'Bengaluru', state: 'Karnataka', pincode: '560001', address: 'Indiranagar, Bengaluru', area: 'Indiranagar', serviceAreas: ['Bengaluru', 'Remote'], budgetMin: 20000, budgetMax: 300000, rating: 4.7, responseTimeMins: 25, conversionRate: 28, revenue: 780000, profileCompletion: 86, approved: true, kycStatus: 'verified', verifiedBadge: true, credits: 25, plan: 'Pro', usp: 'Lead-focused campaigns with weekly ROI reporting.', workingHours: 'Mon-Fri, 9 AM - 6 PM', emergencyAvailable: false, socials: { facebook: 'connected', instagram: 'connected', whatsapp: 'not_connected' }, seo: { title: 'Performance Marketing Agency Bengaluru', keywords: ['lead ads', 'seo', 'paid campaigns'] }, website: { slug: 'pixellaunch', customDomain: '', theme: 'studio', published: true }, services: ['SEO', 'Social Media Marketing', 'Google Ads'], priceRange: '₹₹₹' },
  { id: 'b4', name: 'MachPro Industrial Supplies', category: 'Industrial Machinery', subCategory: 'Packaging Machines', type: 'Product', city: 'Ahmedabad', state: 'Gujarat', pincode: '380015', address: 'Sarkhej, Ahmedabad', area: 'Sarkhej', serviceAreas: ['Ahmedabad', 'Surat', 'Vadodara', 'Rajkot', 'Pan India'], budgetMin: 85000, budgetMax: 1200000, rating: 4.6, responseTimeMins: 12, conversionRate: 31, revenue: 1860000, profileCompletion: 88, approved: true, kycStatus: 'verified', verifiedBadge: true, credits: 37, plan: 'Premium', usp: 'GST-ready industrial machines with installation and AMC support.', workingHours: 'Mon-Sat, 9 AM - 8 PM', emergencyAvailable: false, socials: { facebook: 'connected', instagram: 'not_connected', whatsapp: 'connected' }, seo: { title: 'Packaging Machine Supplier Ahmedabad', keywords: ['packaging machine', 'sealing machine', 'industrial supplier', 'b2b machinery'] }, website: { slug: 'machpro', customDomain: '', theme: 'industrial', published: true }, services: ['Packaging Machines', 'Sealing Machines', 'Industrial Equipment'], priceRange: '₹₹₹' },
  { id: 'b5', name: 'FreshCart Wholesale Foods', category: 'Food & Grocery', subCategory: 'Wholesale Staples', type: 'Product', city: 'Delhi', state: 'Delhi', pincode: '110006', address: 'Khari Baoli, Delhi', area: 'Khari Baoli', serviceAreas: ['Delhi', 'Noida', 'Gurugram', 'Faridabad'], budgetMin: 5000, budgetMax: 250000, rating: 4.4, responseTimeMins: 14, conversionRate: 38, revenue: 920000, profileCompletion: 81, approved: true, kycStatus: 'verified', verifiedBadge: true, credits: 19, plan: 'Pro', usp: 'Bulk grocery supply for retailers, cloud kitchens, and offices.', workingHours: 'All days, 7 AM - 9 PM', emergencyAvailable: true, socials: { facebook: 'connected', instagram: 'connected', whatsapp: 'connected' }, seo: { title: 'Wholesale Grocery Supplier Delhi NCR', keywords: ['wholesale grocery', 'bulk rice', 'office pantry', 'retail supply'] }, website: { slug: 'freshcart-wholesale', customDomain: '', theme: 'fresh', published: true }, services: ['Bulk Rice', 'Pulses Supply', 'Office Pantry'], priceRange: '₹₹' },
  { id: 'b6', name: 'MedEase Clinic Equipment', category: 'Medical Equipment', subCategory: 'Clinic Setup', type: 'Product', city: 'Hyderabad', state: 'Telangana', pincode: '500081', address: 'Madhapur, Hyderabad', area: 'Madhapur', serviceAreas: ['Hyderabad', 'Secunderabad', 'Vijayawada', 'Pan India'], budgetMin: 15000, budgetMax: 900000, rating: 4.7, responseTimeMins: 21, conversionRate: 27, revenue: 1340000, profileCompletion: 79, approved: false, kycStatus: 'pending', verifiedBadge: false, credits: 13, plan: 'Free', usp: 'Clinic furniture, diagnostic equipment, and installation guidance.', workingHours: 'Mon-Fri, 10 AM - 6 PM', emergencyAvailable: false, socials: { facebook: 'not_connected', instagram: 'connected', whatsapp: 'connected' }, seo: { title: 'Clinic Equipment Supplier Hyderabad', keywords: ['medical equipment', 'clinic setup', 'examination table', 'diagnostic kit'] }, website: { slug: 'medease-equipment', customDomain: '', theme: 'medical', published: false }, services: ['Medical Equipment', 'Clinic Setup', 'Diagnostic Tools'], priceRange: '₹₹₹' },
  // === Frontend dummy businesses from data/businesses.js ===
  { id: 'catalog-webnest', name: 'WebNest Solutions', category: 'Web Development', subCategory: 'Website Design', type: 'Service', city: 'Bhubaneswar', state: 'Odisha', pincode: '751024', address: 'Patia, Bhubaneswar', area: 'Patia', serviceAreas: ['Bhubaneswar', 'Remote'], budgetMin: 10000, budgetMax: 200000, rating: 4.8, reviews: 128, responseTimeMins: 20, conversionRate: 30, revenue: 520000, profileCompletion: 85, approved: true, kycStatus: 'verified', verifiedBadge: true, credits: 30, plan: 'Pro', usp: 'Professional website and web app development services for startups and local businesses.', workingHours: 'Mon-Sat, 10 AM - 7 PM', emergencyAvailable: false, socials: { facebook: 'connected', instagram: 'connected', whatsapp: 'connected' }, seo: { title: 'WebNest Solutions Bhubaneswar', keywords: ['web development', 'website design', 'react development', 'bhubaneswar'] }, website: { slug: 'webnest', customDomain: '', theme: 'clean', published: true }, services: ['Website Design', 'React Development', 'SEO Setup'], priceRange: '₹₹' },
  { id: 'catalog-digitalgrow', name: 'DigitalGrow Agency', category: 'Digital Marketing', subCategory: 'SEO Services', type: 'Service', city: 'Bhubaneswar', state: 'Odisha', pincode: '751007', address: 'Saheed Nagar, Bhubaneswar', area: 'Saheed Nagar', serviceAreas: ['Bhubaneswar', 'Remote'], budgetMin: 8000, budgetMax: 150000, rating: 4.6, reviews: 96, responseTimeMins: 25, conversionRate: 28, revenue: 380000, profileCompletion: 82, approved: true, kycStatus: 'verified', verifiedBadge: true, credits: 22, plan: 'Pro', usp: 'SEO, social media marketing, Google Ads, and branding services.', workingHours: 'Mon-Fri, 9 AM - 6 PM', emergencyAvailable: false, socials: { facebook: 'connected', instagram: 'connected', whatsapp: 'not_connected' }, seo: { title: 'Digital Marketing Agency Bhubaneswar', keywords: ['seo', 'social media marketing', 'google ads', 'digital marketing'] }, website: { slug: 'digitalgrow', customDomain: '', theme: 'studio', published: true }, services: ['SEO', 'Social Media Marketing', 'Google Ads'], priceRange: '₹₹₹' },
  { id: 'catalog-fixquick', name: 'FixQuick Services', category: 'Home Services', subCategory: 'AC Repair', type: 'Service', city: 'Cuttack', state: 'Odisha', pincode: '753012', address: 'Badambadi, Cuttack', area: 'Badambadi', serviceAreas: ['Cuttack'], budgetMin: 500, budgetMax: 15000, rating: 4.4, reviews: 78, responseTimeMins: 15, conversionRate: 25, revenue: 185000, profileCompletion: 65, approved: true, kycStatus: 'verified', verifiedBadge: false, credits: 8, plan: 'Free', usp: 'Fast and affordable home repair and maintenance services.', workingHours: 'All days, 8 AM - 9 PM', emergencyAvailable: true, socials: { facebook: 'not_connected', instagram: 'connected', whatsapp: 'connected' }, seo: { title: 'FixQuick Services Cuttack', keywords: ['ac repair', 'home repair', 'electrician', 'cuttack'] }, website: { slug: 'fixquick', customDomain: '', theme: 'bold', published: true }, services: ['AC Repair', 'Washing Machine Repair', 'Electrician'], priceRange: '₹' },
  { id: 'catalog-eventcraft', name: 'EventCraft Odisha', category: 'Event Management', subCategory: 'Wedding Planning', type: 'Service', city: 'Bhubaneswar', state: 'Odisha', pincode: '751005', address: 'Jaydev Vihar, Bhubaneswar', area: 'Jaydev Vihar', serviceAreas: ['Bhubaneswar', 'Cuttack'], budgetMin: 25000, budgetMax: 500000, rating: 4.9, reviews: 210, responseTimeMins: 30, conversionRate: 35, revenue: 850000, profileCompletion: 90, approved: true, kycStatus: 'verified', verifiedBadge: true, credits: 40, plan: 'Premium', usp: 'Complete event planning, wedding decoration, and corporate event management.', workingHours: 'All days, 9 AM - 9 PM', emergencyAvailable: true, socials: { facebook: 'connected', instagram: 'connected', whatsapp: 'connected' }, seo: { title: 'EventCraft Odisha Event Management', keywords: ['event planning', 'wedding decoration', 'corporate events', 'bhubaneswar'] }, website: { slug: 'eventcraft', customDomain: '', theme: 'clean', published: true }, services: ['Wedding Planning', 'Decoration', 'Corporate Events'], priceRange: '₹₹₹' },
  { id: 'catalog-learnpro', name: 'LearnPro Academy', category: 'Education', subCategory: 'Coaching Classes', type: 'Service', city: 'Berhampur', state: 'Odisha', pincode: '760001', address: 'Gandhi Nagar, Berhampur', area: 'Gandhi Nagar', serviceAreas: ['Berhampur', 'Online'], budgetMin: 1000, budgetMax: 50000, rating: 4.5, reviews: 64, responseTimeMins: 40, conversionRate: 24, revenue: 240000, profileCompletion: 75, approved: true, kycStatus: 'verified', verifiedBadge: true, credits: 15, plan: 'Pro', usp: 'Coaching and skill development classes for students and professionals.', workingHours: 'Mon-Sat, 8 AM - 8 PM', emergencyAvailable: false, socials: { facebook: 'connected', instagram: 'connected', whatsapp: 'connected' }, seo: { title: 'LearnPro Academy Berhampur', keywords: ['coaching classes', 'programming classes', 'spoken english', 'berhampur'] }, website: { slug: 'learnpro', customDomain: '', theme: 'clean', published: true }, services: ['Programming Classes', 'Spoken English', 'Exam Preparation'], priceRange: '₹₹' },
  { id: 'catalog-brandspark', name: 'BrandSpark Studio', category: 'Design & Branding', subCategory: 'Logo Design', type: 'Service', city: 'Bhubaneswar', state: 'Odisha', pincode: '751030', address: 'Khandagiri, Bhubaneswar', area: 'Khandagiri', serviceAreas: ['Bhubaneswar', 'Remote'], budgetMin: 3000, budgetMax: 100000, rating: 4.7, reviews: 89, responseTimeMins: 22, conversionRate: 29, revenue: 310000, profileCompletion: 80, approved: true, kycStatus: 'verified', verifiedBadge: true, credits: 18, plan: 'Pro', usp: 'Creative branding, logo design, poster design, and social media creatives.', workingHours: 'Mon-Sat, 10 AM - 7 PM', emergencyAvailable: false, socials: { facebook: 'connected', instagram: 'connected', whatsapp: 'connected' }, seo: { title: 'BrandSpark Studio Bhubaneswar', keywords: ['logo design', 'poster design', 'brand identity', 'bhubaneswar'] }, website: { slug: 'brandspark', customDomain: '', theme: 'studio', published: true }, services: ['Logo Design', 'Poster Design', 'Brand Identity'], priceRange: '₹₹' }
];

// Map each service to a business that offers it
const serviceToBusinessId = {
  'Interior Design': 'b1',       // UrbanNest Interiors
  'AC Repair': 'catalog-fixquick',     // FixQuick Services
  'Home Cleaning': 'catalog-fixquick', // FixQuick Services
  'Painting Service': 'catalog-fixquick', // FixQuick Services
  'Plumbing Service': 'b2',      // SwiftFix Plumbing
  'Electrical Repair': 'b2'      // SwiftFix Plumbing
};

const serviceRows = [
  ['Interior Design', '₹15,000', 'Modern interior solutions for homes and offices.', 'https://images.unsplash.com/photo-1484154218962-a197022b5858', [['Basic Interior', '₹5000', ['1 Room Design', 'Basic Support', '2D Layout']], ['Premium Interior', '₹15000', ['Full Home Design', 'Premium Support', '3D Layout']]]],
  ['AC Repair', '₹999', 'Professional AC repair and maintenance services.', 'https://images.unsplash.com/photo-1621905251918-48416bd8575a', [['AC Basic Service', '₹999', ['Gas Check', 'Cleaning', 'Basic Repair']], ['AC Full Repair', '₹2500', ['Complete Repair', 'Cooling Fix', 'Installation']]]],
  ['Home Cleaning', '₹2,500', 'Deep cleaning services for apartments and houses.', 'https://images.unsplash.com/photo-1527515637462-cff94eecc1ac', [['Cleaning Basic', '₹1500', ['Kitchen Cleaning', 'Dust Removal', 'Bathroom Cleaning']]]],
  ['Painting Service', '₹8,000', 'Premium wall painting and decoration services.', 'https://images.unsplash.com/photo-1562259949-e8e7689d7828', [['Painting Basic', '₹3000', ['Wall Painting', 'Color Selection', '1 Room Paint']]]],
  ['Plumbing Service', '₹700', 'Quick plumbing fixes and installation services.', 'https://images.unsplash.com/photo-1581578731548-c64695cc6952', [['Plumbing Basic', '₹1200', ['Leak Repair', 'Tap Fixing', 'Pipe Cleaning']]]],
  ['Electrical Repair', '₹1,200', 'Expert electrical maintenance and repair solutions.', 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4', [['Electrical Basic', '₹1800', ['Wiring Check', 'Switch Repair', 'Installation']]]]
];

export const catalogServices = serviceRows.map(([title, priceLabel, description, image, packages], index) => ({
  id: `catalog-service-${index + 1}`, 
  title, 
  priceLabel, 
  description, 
  image,
  businessId: serviceToBusinessId[title] || '',
  category: title === 'Interior Design' ? 'Interior Design' : 'Home Services',
  tags: [title], 
  packages: packages.map(([name, price, features]) => ({ name, price, features })), 
  status: 'approved'
}));
