import bcrypt from 'bcryptjs';

const hashPassword = (password) => bcrypt.hashSync(password, 10);

export const db = {
  users: [
    { 
      id: 'u1', name: 'Aarav Mehta', email: 'customer@demo.com', phone: '9876543210', 
      role: 'user', verified: true, blocked: false, favorites: ['b1'], 
      referralCode: 'AARAV50', activity: ['Logged in', 'Posted interior design requirement'],
      passwordHash: hashPassword('User123@')
    },
    { 
      id: 'u2', name: 'Nisha Rao', email: 'vendor@demo.com', phone: '9876500001', 
      role: 'business_owner', verified: true, blocked: false, businessId: 'b1',
      vendorStatus: 'approved',
      activity: ['Updated lead status', 'Scheduled WhatsApp follow-up'],
      passwordHash: hashPassword('Vendor123@')
    },
    { 
      id: 'u3', name: 'Admin User', email: 'admin@demo.com', phone: '9000000001', 
      role: 'admin', verified: true, blocked: false, 
      approved: true, vendorStatus: 'approved',
      activity: ['Approved vendor profile'],
      passwordHash: hashPassword('Admin123@')
    },
    { 
      id: 'u4', name: 'Super Admin', email: 'superadmin@demo.com', phone: '9000000002', 
      role: 'super_admin', verified: true, blocked: false,
      approved: true, vendorStatus: 'approved',
      activity: ['Changed platform rules'],
      passwordHash: hashPassword('SuperAdmin123@')
    },
    { 
      id: 'u_admin', name: 'Nikhil Admin', email: 'nikhil@admin.com', phone: '9000000000', 
      role: 'admin', verified: true, blocked: false,
      approved: true, vendorStatus: 'approved',
      activity: ['Default admin account created'],
      passwordHash: hashPassword('Nikhil26@')
    }
  ],
  businesses: [
    {
      id: 'b1',
      ownerId: 'u2',
      name: 'UrbanNest Interiors',
      ownerName: 'Nisha Rao',
      category: 'Interior Design',
      subCategory: 'Home Renovation',
      type: 'Service',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400001',
      address: 'Fort, Mumbai',
      serviceAreas: ['Mumbai', 'Thane', 'Navi Mumbai'],
      budgetMin: 50000,
      budgetMax: 800000,
      rating: 4.8,
      responseTimeMins: 18,
      conversionRate: 34,
      revenue: 1250000,
      profileCompletion: 92,
      approved: true,
      kycStatus: 'verified',
      verifiedBadge: true,
      credits: 42,
      plan: 'Premium',
      usp: 'End-to-end interiors with transparent milestones.',
      workingHours: 'Mon-Sat, 10 AM - 7 PM',
      emergencyAvailable: true,
      socials: { facebook: 'connected', instagram: 'connected', whatsapp: 'connected' },
      seo: { title: 'UrbanNest Interiors Mumbai', keywords: ['interior designer', '2BHK renovation', 'modular kitchen'] },
      website: { slug: 'urbannest', customDomain: '', theme: 'clean', published: true }
    },
    {
      id: 'b2',
      ownerId: 'u2',
      name: 'SwiftFix Plumbing',
      ownerName: 'Nisha Rao',
      category: 'Home Services',
      subCategory: 'Plumbing',
      type: 'Service',
      city: 'Pune',
      state: 'Maharashtra',
      pincode: '411001',
      address: 'Koregaon Park, Pune',
      serviceAreas: ['Pune', 'PCMC'],
      budgetMin: 500,
      budgetMax: 25000,
      rating: 4.5,
      responseTimeMins: 9,
      conversionRate: 41,
      revenue: 420000,
      profileCompletion: 74,
      approved: true,
      kycStatus: 'verified',
      verifiedBadge: true,
      credits: 11,
      plan: 'Pro',
      usp: 'Emergency repairs with same-day visits.',
      workingHours: 'All days, 8 AM - 10 PM',
      emergencyAvailable: true,
      socials: { facebook: 'not_connected', instagram: 'connected', whatsapp: 'connected' },
      seo: { title: 'Emergency Plumber Pune', keywords: ['plumber near me', 'leak repair'] },
      website: { slug: 'swiftfix', customDomain: '', theme: 'bold', published: false }
    },
    {
      id: 'b3',
      ownerId: 'u2',
      name: 'PixelLaunch Marketing',
      ownerName: 'Nisha Rao',
      category: 'Digital Marketing',
      subCategory: 'Performance Ads',
      type: 'Service',
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '560001',
      address: 'Indiranagar, Bengaluru',
      serviceAreas: ['Bengaluru', 'Remote'],
      budgetMin: 20000,
      budgetMax: 300000,
      rating: 4.7,
      responseTimeMins: 25,
      conversionRate: 28,
      revenue: 780000,
      profileCompletion: 86,
      approved: true,
      kycStatus: 'verified',
      verifiedBadge: true,
      credits: 25,
      plan: 'Pro',
      usp: 'Lead-focused campaigns with weekly ROI reporting.',
      workingHours: 'Mon-Fri, 9 AM - 6 PM',
      emergencyAvailable: false,
      socials: { facebook: 'connected', instagram: 'connected', whatsapp: 'not_connected' },
      seo: { title: 'Performance Marketing Agency Bengaluru', keywords: ['lead ads', 'seo', 'paid campaigns'] },
      website: { slug: 'pixellaunch', customDomain: '', theme: 'studio', published: true }
    },
    {
      id: 'b4',
      ownerId: 'u2',
      name: 'MachPro Industrial Supplies',
      ownerName: 'Nisha Rao',
      category: 'Industrial Machinery',
      subCategory: 'Packaging Machines',
      type: 'Product',
      city: 'Ahmedabad',
      state: 'Gujarat',
      pincode: '380015',
      address: 'Sarkhej, Ahmedabad',
      serviceAreas: ['Ahmedabad', 'Surat', 'Vadodara', 'Rajkot', 'Pan India'],
      budgetMin: 85000,
      budgetMax: 1200000,
      rating: 4.6,
      responseTimeMins: 12,
      conversionRate: 31,
      revenue: 1860000,
      profileCompletion: 88,
      approved: true,
      kycStatus: 'verified',
      verifiedBadge: true,
      credits: 37,
      plan: 'Premium',
      usp: 'GST-ready industrial machines with installation and AMC support.',
      workingHours: 'Mon-Sat, 9 AM - 8 PM',
      emergencyAvailable: false,
      socials: { facebook: 'connected', instagram: 'not_connected', whatsapp: 'connected' },
      seo: { title: 'Packaging Machine Supplier Ahmedabad', keywords: ['packaging machine', 'sealing machine', 'industrial supplier', 'b2b machinery'] },
      website: { slug: 'machpro', customDomain: '', theme: 'industrial', published: true }
    },
    {
      id: 'b5',
      ownerId: 'u2',
      name: 'FreshCart Wholesale Foods',
      ownerName: 'Nisha Rao',
      category: 'Food & Grocery',
      subCategory: 'Wholesale Staples',
      type: 'Product',
      city: 'Delhi',
      state: 'Delhi',
      pincode: '110006',
      address: 'Khari Baoli, Delhi',
      serviceAreas: ['Delhi', 'Noida', 'Gurugram', 'Faridabad'],
      budgetMin: 5000,
      budgetMax: 250000,
      rating: 4.4,
      responseTimeMins: 14,
      conversionRate: 38,
      revenue: 920000,
      profileCompletion: 81,
      approved: true,
      kycStatus: 'verified',
      verifiedBadge: true,
      credits: 19,
      plan: 'Pro',
      usp: 'Bulk grocery supply for retailers, cloud kitchens, and offices.',
      workingHours: 'All days, 7 AM - 9 PM',
      emergencyAvailable: true,
      socials: { facebook: 'connected', instagram: 'connected', whatsapp: 'connected' },
      seo: { title: 'Wholesale Grocery Supplier Delhi NCR', keywords: ['wholesale grocery', 'bulk rice', 'office pantry', 'retail supply'] },
      website: { slug: 'freshcart-wholesale', customDomain: '', theme: 'fresh', published: true }
    },
    {
      id: 'b6',
      ownerId: 'u2',
      name: 'MedEase Clinic Equipment',
      ownerName: 'Nisha Rao',
      category: 'Medical Equipment',
      subCategory: 'Clinic Setup',
      type: 'Product',
      city: 'Hyderabad',
      state: 'Telangana',
      pincode: '500081',
      address: 'Madhapur, Hyderabad',
      serviceAreas: ['Hyderabad', 'Secunderabad', 'Vijayawada', 'Pan India'],
      budgetMin: 15000,
      budgetMax: 900000,
      rating: 4.7,
      responseTimeMins: 21,
      conversionRate: 27,
      revenue: 1340000,
      profileCompletion: 79,
      approved: true,
      kycStatus: 'verified',
      verifiedBadge: true,
      credits: 13,
      plan: 'Free',
      usp: 'Clinic furniture, diagnostic equipment, and installation guidance.',
      workingHours: 'Mon-Fri, 10 AM - 6 PM',
      emergencyAvailable: false,
      socials: { facebook: 'not_connected', instagram: 'connected', whatsapp: 'connected' },
      seo: { title: 'Clinic Equipment Supplier Hyderabad', keywords: ['medical equipment', 'clinic setup', 'examination table', 'diagnostic kit'] },
      website: { slug: 'medease-equipment', customDomain: '', theme: 'medical', published: true }
    }
  ],
  listings: [
    { id: 'l1', businessId: 'b1', type: 'Package', title: '2BHK Complete Interior Package', category: 'Interior Design', priceType: 'Starting Price', price: 300000, discountPrice: 275000, status: 'approved', views: 1880, clicks: 318, leads: 44, conversionRate: 31, tags: ['2BHK', 'modular kitchen'], actions: ['Enquiry', 'WhatsApp', 'Call', 'Get Quote'], packages: [{ name: 'Basic', price: 300000 }, { name: 'Premium', price: 650000 }] },
    { id: 'l2', businessId: 'b2', type: 'Service', title: 'Emergency Plumbing Visit', category: 'Home Services', priceType: 'Fixed Price', price: 799, discountPrice: 699, status: 'approved', views: 620, clicks: 142, leads: 26, conversionRate: 45, tags: ['emergency', 'leak'], actions: ['Book Now', 'WhatsApp', 'Call'], packages: [] },
    { id: 'l3', businessId: 'b3', type: 'Service', title: 'Lead Generation Ads Sprint', category: 'Digital Marketing', priceType: 'Price Range', price: 45000, discountPrice: 40000, status: 'approved', views: 980, clicks: 201, leads: 31, conversionRate: 22, tags: ['ads', 'lead generation'], actions: ['Enquiry', 'Get Quote'], packages: [{ name: 'Standard', price: 75000 }] },
    { id: 'l4', businessId: 'b4', type: 'Product', title: 'Automatic Pouch Packing Machine', category: 'Industrial Machinery', priceType: 'Starting Price', price: 285000, discountPrice: 265000, status: 'approved', views: 2210, clicks: 402, leads: 58, conversionRate: 29, tags: ['packaging machine', 'pouch packing', 'industrial'], actions: ['Enquiry', 'Get Latest Price', 'Call', 'Compare'], packages: [{ name: 'Semi Automatic', price: 145000 }, { name: 'Automatic', price: 285000 }] },
    { id: 'l5', businessId: 'b4', type: 'Product', title: 'Band Sealing Machine with Conveyor', category: 'Industrial Machinery', priceType: 'Fixed Price', price: 92000, discountPrice: 87500, status: 'approved', views: 1330, clicks: 244, leads: 37, conversionRate: 26, tags: ['sealing machine', 'conveyor', 'manufacturing'], actions: ['Enquiry', 'WhatsApp', 'Get Quote'], packages: [] },
    { id: 'l6', businessId: 'b5', type: 'Product', title: 'Bulk Basmati Rice and Pulses Supply', category: 'Food & Grocery', priceType: 'Wholesale Price', price: 5200, discountPrice: 4900, status: 'approved', views: 1740, clicks: 330, leads: 49, conversionRate: 36, tags: ['rice', 'pulses', 'wholesale grocery', 'retail supply'], actions: ['Enquiry', 'WhatsApp', 'Call'], packages: [{ name: '100 kg lot', price: 9800 }, { name: '500 kg lot', price: 46500 }] },
    { id: 'l7', businessId: 'b6', type: 'Product', title: 'Clinic Examination Table and Diagnostic Kit', category: 'Medical Equipment', priceType: 'Starting Price', price: 36000, discountPrice: 34000, status: 'approved', views: 790, clicks: 128, leads: 16, conversionRate: 18, tags: ['clinic setup', 'medical equipment', 'diagnostic'], actions: ['Enquiry', 'Get Quote'], packages: [{ name: 'Basic Clinic Kit', price: 118000 }] }
  ],
  leads: [
    { id: 'lead1', customerId: 'u1', name: 'Aarav Mehta', mobile: '9876543210', category: 'Interior Design', requirement: 'Need interior designer for 2BHK, modern style, budget 3L', budget: 300000, location: 'Mumbai', timeline: '30 days', source: 'Post Requirement', score: 'Hot', status: 'New', assignedTo: 'Nisha Rao', businessIds: ['b1'], notes: ['OTP verified', 'Auto matched by category and city'], followUpAt: 'Tomorrow 11:00 AM', createdAt: '2026-05-12' },
    { id: 'lead2', customerId: 'u1', name: 'Aarav Mehta', mobile: '9876543210', category: 'Home Services', requirement: 'Kitchen sink leakage repair', budget: 2000, location: 'Pune', timeline: 'Today', source: 'WhatsApp click', score: 'Hot', status: 'Contacted', assignedTo: 'Nisha Rao', businessIds: ['b2'], notes: ['WhatsApp auto-reply sent'], followUpAt: 'In 1 hour', createdAt: '2026-05-12' },
    { id: 'lead3', customerId: 'u1', name: 'Aarav Mehta', mobile: '9876543210', category: 'Digital Marketing', requirement: 'Need B2B lead generation for SaaS', budget: 100000, location: 'Bengaluru', timeline: '2 weeks', source: 'Product enquiry', score: 'Warm', status: 'Follow-up', assignedTo: 'Nisha Rao', businessIds: ['b3'], notes: ['Quotation requested'], followUpAt: '2026-05-14 15:00', createdAt: '2026-05-11' }
  ],
  reviews: [
    { id: 'r1', businessId: 'b1', userId: 'u1', user: 'Aarav Mehta', rating: 5, text: 'Clear pricing and quick design proposal.', verifiedWork: true, media: ['before-after.jpg'], authenticityScore: 96 },
    { id: 'r2', businessId: 'b3', userId: 'u1', user: 'Aarav Mehta', rating: 4, text: 'Good campaign plan and reporting.', verifiedWork: true, media: [], authenticityScore: 91 }
  ],
  campaigns: [
    { id: 'c1', businessId: 'b1', channel: 'WhatsApp', title: 'Summer renovation offer', status: 'scheduled', scheduledFor: '2026-05-13 10:00', engagement: 68 },
    { id: 'c2', businessId: 'b3', channel: 'Instagram', title: 'Free ads audit', status: 'posted', scheduledFor: '2026-05-10 12:00', engagement: 42 }
  ],
  subscriptions: [
    { id: 's1', name: 'Free', price: 0, leadLimit: 5, features: ['Basic profile', 'Limited leads'] },
    { id: 's2', name: 'Pro', price: 1999, leadLimit: 50, features: ['Filtered leads', 'CRM', 'Email alerts'] },
    { id: 's3', name: 'Premium', price: 4999, leadLimit: 200, features: ['Priority leads', 'Automation', 'Broadcasts', 'Instant connect'] }
  ],
  notifications: [
    { id: 'n1', audience: 'vendor', title: 'New Lead Received', body: 'Aarav needs Interior Design in Mumbai', channel: 'dashboard,email,whatsapp', read: false },
    { id: 'n2', audience: 'business', title: 'Your profile is approved', body: 'UrbanNest Interiors is live with a verified badge.', channel: 'email', read: true }
  ],
  activityLogs: [
    { id: 'a1', actor: 'Admin User', action: 'Approved UrbanNest Interiors profile', risk: 'low' },
    { id: 'a2', actor: 'System', action: 'Detected duplicate plumbing lead attempt', risk: 'medium' }
  ],
  platformConfig: {
    whatsappApi: 'mock',
    paymentGateway: 'mock',
    leadDistributionLimit: 5,
    fakeLeadRefund: true,
    profileLockThreshold: 80,
    roles: ['Owner', 'Manager', 'Sales Staff', 'Marketing Staff', 'Admin', 'Moderator', 'Super Admin', 'Technical Admin', 'Finance Admin']
  }
};